---
title: User Presence with Notifications
description: Getting and setting the current user's presence and listening for changes.
categories:
- Status
- Notifications
steps:
- title: Introduction
  content: |
    This tutorial will walk through the steps of getting the current user's status, how to listen for notifications when the presence is changed, and how to update their status.

    For more information on the Presence APIs see the [REST Documentation](https://developer.mypurecloud.com/api/rest/v2/presence/index.html) and the [Understanding Presence](https://developer.mypurecloud.com/api/rest/v2/presence/understanding_presence.html) guide.

- title: Get Current Presence State
  content: |
    After authorizing your application, you can get all of the presences defined in the system to provide the user with controls to change their presence.

    You will also want to get the current user's information, which contains a reference to their presence. Using the presence definition ID, you can get the presence definition data.

- title: Registering for Notifications
  content: |
    In order to receive notifications, we must first create a channel.  The result of the channel create will give us a websocket URI that we can connect to. We will then create a subscription on that channel for the current user's status.

- title: Receiving Web Socket Events
  content: |
    The web socket messages will contain a payload in the eventBody property that looks similar to this:

    ```{"language":"json"}
    {
      "topicName": "v2.users.9ed7d9f6-0c59-4360-ac54-40dd35eb9c2f.presence",
      "version": "2",
      "eventBody": {
      "source": "PURECLOUD",
      "presenceDefinition": {
        "id": "6a3af858-942f-489d-9700-5f9bcdcdae9b",
        "systemPresence": "AVAILABLE"
      },
      "primary": true,
      "message": ""
      },
      "metadata": {
        "CorrelationId": "290034f4-c3d7-46fd-8342-ee5bc859b7e9"
      }
    }
    ```

    Here, eventBody contains a value of status which should mimic what you would get from the status property on the user object.

- title: Updating Presence
  content: |
    Finally, we can update the presence.  The call to update the presence requires a "Source Id". Genesys Cloud could potentially have different status sources from external systems, but here we want to update the Genesys Cloud status so we can pass in the key of _PURECLOUD_.

languages: 
  javascript:
    displayName: JavaScript
    steps:
    - file: "javascript/index.html"
      highlight: "0-160"
    - file: "javascript/index.html"
      highlight: "45-65"
    - file: "javascript/index.html"
      highlight: "70-87"
    - file: "javascript/index.html"
      highlight: "103-126"
    - file: "javascript/index.html"
      highlight: "92-101"
  java:
    displayName: Java
    steps:
    - file: "java/src/com/genesys/Main.java"
      highlight: "0-104"
    - file: "java/src/com/genesys/Main.java"
      highlight: "28-63"
    - file: "java/src/com/genesys/Main.java"
      highlight: "1-1"
      note: The java example currently does not implement presence notifications.
    - file: "java/src/com/genesys/Main.java"
      highlight: "1-1"
      note: The java example currently does not implement presence notifications.
    - file: "java/src/com/genesys/Main.java"
      highlight: "80-99"
