---
title: Uploading Architect Prompts
description: Creating a prompt and uploading media
categories:
- Architect
steps:
- title: Introduction
  content: |
    Programmatically uploading prompts is done in three steps: 1) creating the prompt object, 2) creating the prompt's resource, and 3) uploading the prompt's media file.

- title: Authenticate with PureCloud
  content: |
    The OAuth Client Credentials are retrieved from environment variables and used to authenticate with PureCloud.

- title: Create an Organization
  content: |
    First, the prompt object is created. This API only requires the name of the prompt, though a description will be useful when viewing prompts in Architect.

- title: Create Users
  content: |
    Next, the prompt resource is created. This requires the ID from the prompt created in the previous step as well as the language of the prompt. The value for `language` must be a known Architect language code. 

- title: Create Users
  content: |
    Using the upload URI returned from creating the prompt resource, upload the media file for the prompt. This POST request requires the Authorization header to be specified. The prompt media should be provided in the form-data property `file`.

languages: 
  nodejs:
    displayName: NodeJS
    steps:
    - file: "nodejs/index.js"
      highlight: "0-100"
    - file: "nodejs/index.js"
      highlight: "5-19"
    - file: "nodejs/index.js"
      highlight: "21-31"
    - file: "nodejs/index.js"
      highlight: "33-42"
    - file: "nodejs/index.js"
      highlight: "44-60"
