---
  title: Premium Applications - Usage APIs
  description: This tutorial provides sample code for Premium Applications - Usage APIs
  categories:
  - Usage
  steps:
  - title: Introduction
    content: |
      This tutorial provides a sample code on how to use the Premium Applications - Usage APIs. The Usage APIs allow Premium Application vendors to get the customer usage of their Premium Applications.
      There are three (3) separate APIs for granularity:

      * Overall Customer Count: Total number of customers per Genesys Cloud Region
      * Usage per Customer within a Region: Current usage quantity per customer within a Genesys Cloud Region, includes Org Name and Org Id
      * Individual Customer Subscription: Customer subscription details

      Read more about Premium Applications - Usage APIs in this [link](/appfoundry/premium-vendor-usage.html#individual_customer_subscription).
  
  - title: Variable Declaration
    content: |
      The **apiKey** and **appId** are prerequisites to be able to use Premium Applications - Usage APIs.

        * **apiKey** - All vendors will need an apiKey to use our Premium Applications - Usage APIs. Vendors of Premium Applications - Metered Type already have an apiKey. Vendors of Premium Applications - Usage Type, please contact the AppFoundry team at appfoundry@genesys.com for the unique **apiKey**.
        * **appId** - For this tutorial, **samplePremiumApp** is our sample **appId**. Multiple appIds may be requested in a single GET request by adding a comma between appIds without a space. Example: **samplePremiumApp,secondSamplePremiumApp**

      With the **apiKey** and **appId** provided, start by calling the first Usage API. 
  - title: Overall Customer Count
    content: |
      The first API call returns customer counts that uses **samplePremiumApp** per Genesys Cloud region.
      The sample code will loop through the payload and for each region with **organizationCounts**  
      greater than zero, the program will call the next Usage API function. 
      
      
      ```{"language":"json"}
      --- OVERALL CUSTOMER COUNT ---
      {
        "regions": [
          {
            "id": "ca-central-1",
            "organizationCounts": {
              "samplePremiumApp": 2
            }
          },
          {
            "id": "ap-northeast-1",
            "organizationCounts": {
              "samplePremiumApp": 0
            }
          },
          {
            "id": "eu-central-1",
            "organizationCounts": {
                "samplePremiumApp": 1
            }
          }
        ]  
      }
      ```
  - title: Usage Per Customer Within Region
    content: |
      The second API call returns customer specific usage counts by Genesys Cloud region. Following the flow of the program, 
      we are now getting the customer usage in the first region of the previous payload - **'ca-central-1'**. 
      The returned data below are the two organizations from the **ca-central-1** region showing the usage count per organization.

      The program will loop through each organization and get the **orgId**. Then continue to the next function that will provide subscription details of each organization ID.
      
      ```{"language":"json"}
      --- CUSTOMER FROM REGION ca-central-1 ---
      {
        "organizations": [
          {
            "orgId": "1aa11a1a-1111-1a11-1a11-11a1a111a1aa",
            "orgName": "First Sample OrgName",
            "usageQuantities": {
              "samplePremiumApp": 825
            }
          },
          {
            "orgId": "2bb22b2b-2222-2b22-2b22-22b2b222b2bb",
            "orgName": "Second Sample OrgName",
            "usageQuantities": {
              "samplePremiumApp": 15
            }
          }
        ]
      }
      ```   
  - title: Individual Customer Subscription
    content: |
      The third API call returns subscription information about a vendor's Premium Application(s). The sample return below shows the subscription details of 'First Sample OrgName'.

      ```{"language":"json"}
      --- SUBSCRIPTION FROM REGION ca-central-1, FROM ORG 1aa11a1a-1111-1a11-1a11-11a1a111a1aa ---
      {
        "orgId": "1aa11a1a-1111-1a11-1a11-11a1a111a1aa",
        "orgName": "First Sample OrgName",
        "contractStartDate": "2018-10-01T00:00:00.000Z",
        "contractEndDate": "2024-12-31T23:59:59.999Z",
        "rampPeriodStartDate": "2018-09-28T00:00:00.000Z",
        "rampPeriodEndDate": "2018-12-31T23:59:59.999Z",
        "billingPeriodStartDate": "2020-05-01T00:00:00.000Z",
        "billingPeriodEndDate": "2020-05-31T23:59:59.999Z",
        "currency": "USD",
        "subscriptionType": "PREPAY",
        "usages": [
          {
            "appId": "samplePremiumApp",
            "chargeName": "Sample Premium Application for Genesys Cloud",
            "partNumber": "PC-170-NV-PCSAMPLE",
            "prepayQuantity": 1000,
            "prepayPrice": "60.080000",
            "usageQuantity": 825,
            "usagePrice": "6.700000"
          }
        ]
      }
      ```
  - title: Sample Payload
    content: |
      After looping through each region and organization, you should receive a payload just like the example shown. 

  languages:
    nodejs:
      displayName: NodeJS
      steps:
      - file: "nodejs/index.js"
        highlight: "0-69"
      - file: "nodejs/index.js"
        highlight: "1-8"
      - file: "nodejs/index.js"
        highlight: "10-32"
      - file: "nodejs/index.js"
        highlight: "34-53"
      - file: "nodejs/index.js"
        highlight: "55-69"
      - file: "nodejs/result.json"
        highlight: "1-122"